// torrent.ts — helpers for classifying sources and picking torrent files.
// Multi-video playlists are now generated by the daemon's /play endpoint
// (audio/x-mpegurl response), so the plugin no longer writes any .m3u file
// itself.
//
// File-type classification (video / subtitle) lives entirely on the daemon
// side (isVideoFile / isSubtitleFile in engine.go). The plugin reads the
// resulting FileStatus.isVideo / isSubtitle booleans — so the list of
// recognised extensions has a single source of truth instead of drifting
// between TypeScript and Go.

import type { TorrentStatus, FileStatus } from "./daemon";

const TORRENT_FILE_EXT = /\.torrent$/i;

/** Returns the last path component of a (forward-slash) path. */
export function fileBaseName(path: string): string {
  const parts = path.split("/");
  return parts[parts.length - 1] || path;
}

/** Reports whether a URL/path is a torrent source this plugin should handle. */
export function isTorrentSource(url: string): boolean {
  if (!url) return false;
  const trimmed = url.trim().toLowerCase();
  if (trimmed.startsWith("magnet:")) return true;
  // Strip any query string AND fragment before checking the extension —
  // otherwise URLs like "https://host/file.torrent#section" fail to match.
  return TORRENT_FILE_EXT.test(trimmed.split(/[?#]/)[0]);
}

/** Returns the video files contained in the torrent, in torrent order. */
export function videoFiles(info: TorrentStatus): FileStatus[] {
  return info.files.filter((f) => f.isVideo);
}

/** Returns the subtitle files contained in the torrent, in torrent order. */
export function subtitleFiles(info: TorrentStatus): FileStatus[] {
  return info.files.filter((f) => f.isSubtitle);
}

